trigger:
- none

pool:
  vmImage: ubuntu-latest

steps:

- script: |
    curl -L -o jdk16.tar.gz https://github.com/adoptium/temurin16-binaries/releases/download/jdk-16.0.2+7/OpenJDK16U-jdk_x64_linux_hotspot_16.0.2_7.tar.gz
    mkdir -p /tmp/jdk16
    tar -xzf jdk16.tar.gz -C /tmp/jdk16 --strip-components=1
    echo "##vso[task.setvariable variable=JAVA_HOME]/tmp/jdk16"
    echo "##vso[task.prependpath]/tmp/jdk16/bin"
  displayName: 'Install Java 16 manually'

# Run Maven using bash script, making sure JAVA_HOME is set in the environment
- script: |
    echo "Java version:"
    java -version

    echo "Maven version:"
    mvn -version

    echo "Running Maven build with cucumber tag @sanity"
    export PATH=$JAVA_HOME/bin:$PATH
    mvn clean test -Dcucumber.filter.tags="@sanity"

    echo "Listing surefire reports directory:"
    ls -l target/surefire-reports/

    echo "Listing test results XML files:"
    ls -l target/surefire-reports/TEST-*.xml
    
  displayName: 'Run Maven build with Java 21'
