steps:
- task: UseJavaVersion@1
  inputs:
    versionSpec: '17'
    jdkArchitecture: 'x64'

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean test'
    options: '-Dcucumber.filter.tags="@sanity"'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'Path'
    jdkDirectory: $(JAVA_HOME_17_X64)
    mavenVersionOption: 'Default'
    mavenOptions: '-Xmx3072m'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
