trigger:
- none

pool:
  vmImage: ubuntu-latest

parameters:
  - name: cucumberTag
    type: string
    default: '@sanity' 

steps:
# Install Java 16
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '21'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'
    
- script: |
    echo "Java version:"
    java -version

    echo "Maven version:"
    mvn -version
    
    echo "Listing root directory before running test:"
    ls -lR

    export PATH=$JAVA_HOME/bin:$PATH
    mvn clean install
    mvn compile
  displayName: 'Run Maven build'

- script: |
    echo "Running Maven build with cucumber tag '${{ parameters.cucumberTag }}'"
    mvn test -Dcucumber.filter.tags="${{ parameters.cucumberTag }}"  
  displayName: 'Run Maven Tests'

- script: |
    echo "Listing root directory:"
    ls -lR
displayName: 'Listing files'
