trigger:
- none

pool:
  vmImage: ubuntu-latest

steps:
# Install Java 21
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '16'
    jdkArchitectureOption: 'x64'

# Run Maven using bash script, making sure JAVA_HOME is set in the environment
- script: |
    echo "Java version:"
    java -version

    echo "Maven version:"
    mvn -version

    echo "Running Maven build with cucumber tag @sanity"
    export PATH=$JAVA_HOME/bin:$PATH
    mvn clean test -Dcucumber.filter.tags="@sanity"

    echo "Listing surefire reports directory:"
    ls -l target/surefire-reports/

    echo "Listing test results XML files:"
    ls -l target/surefire-reports/TEST-*.xml
    
  displayName: 'Run Maven build with Java 21'
