trigger:
- none

pool:
  vmImage: ubuntu-latest

steps:
# Install Java 16
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '21'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'
    
- script: |
    echo "Java version:"
    java -version

    echo "Maven version:"
    mvn -version
    
    echo "Listing root directory before running test:"
    ls -lR

    # echo "Running Maven build with cucumber tag @sanity"
    export PATH=$JAVA_HOME/bin:$PATH
    mvn clean install
    mvn compile
    mvn test -Dcucumber.filter.tags="@PageSpeed"
    
    echo "Listing root directory:"
    ls -lR
  
  displayName: 'Run Maven build'
