trigger:
- none

pool:
  vmImage: ubuntu-latest

steps:
# Install Java 16
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '21'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'
    

- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean test'
    options: '-Dcucumber.filter.tags="@sanity"'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'Path'
    jdkDirectory: $(JAVA_HOME_21_X64)
    mavenVersionOption: 'Default'
    mavenOptions: '-Xmx3072m'

- script: |
    echo "Listing root directory:"
    ls -lR
  displayName: 'Listing files'

